---
name: csvn

releases:
- name: subversion-edge
  version: 
  url: 
  sha1: 

instance_groups:
- name: csvn
  instances: 1
  vm_type:   default
  stemcell:  default
  azs:       [z1]
  networks:
  - name:    default
  persistent_disk: 2048
  jobs:
  - name:    csvn
    release: subversion-edge
    properties:
      bpm:
        enabled: true

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest
