#!/bin/bash

# NOTE: PIDFILE is only used as a signal for Monit!

RUN_DIR=/var/vcap/sys/run/csvn
LOG_DIR=/var/vcap/sys/log/csvn
PIDFILE=${RUN_DIR}/csvn.pid

source /var/vcap/packages/openjdk-8/bosh/runtime.env
source /var/vcap/packages/python-2.7/bosh/runtime.env

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    cd /var/vcap/store/csvn/appserver
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/var/vcap/store/csvn/lib
    java -Djetty.home=/var/vcap/store/csvn/appserver -Djetty.port=3343 -Djetty.ssl.port=4434 -jar start.jar \
      >>  $LOG_DIR/jetty.stdout.log \
      2>> $LOG_DIR/jetty.stderr.log

    ;;

  stop)
    pkill --full jetty.home
    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}" ;;

esac
