#!/bin/bash

# We use the PID file that Apache writes out.
# Since CSVN manages the Apache configuration files, we cannot simply
# provide our own (see monit file for pid location).

RUN_DIR=/var/vcap/sys/run/csvn
LOG_DIR=/var/vcap/sys/log/csvn

source /var/vcap/packages/python-2.7/bosh/runtime.env

case $1 in

  start)
    mkdir -p $LOG_DIR
    chown -R vcap:vcap $LOG_DIR

    cd /var/vcap/store/csvn

    # Replace "Listen 80" with "Listen 18080"? Will CSVN see this?

    bin/httpd -f /var/vcap/store/csvn/data/conf/httpd.conf -k start \
      >>  $LOG_DIR/httpd.stdout.log \
      2>> $LOG_DIR/httpd.stderr.log

    ;;

  stop)

    cd /var/vcap/store/csvn

    bin/httpd -f /var/vcap/store/csvn/data/conf/httpd.conf -k stop \
      >>  $LOG_DIR/httpd.stdout.log \
      2>> $LOG_DIR/httpd.stderr.log

    ;;

  *)
    echo "Usage: ctl-httpd {start|stop}" ;;

esac
